In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'>

In [3]:
#lista sequencial de numeros
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(5,10,.1)

array([5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2,
       6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5,
       7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8,
       8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [6]:
#lista do numpy eh mais rapida, mas so aceita numeros
np.array([3,6,4,9])

array([3, 6, 4, 9])

In [7]:
a = np.array([2,3,4,5])

In [8]:
a

array([2, 3, 4, 5])

In [9]:
a.sum()

14

In [10]:
np.diff(a)

array([1, 1, 1])